version: '3.7'

services:

  app:
    stdin_open: true
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # map volumes to hot reload work
      - ./app:/app
      - ./app/node_modules:/app/node_modules
    ports:
      - 3001:3000